modLoader = "javafml"
loaderVersion = "[25,)"
license = "All Rights Reserved"

[[mods]]
    modId = "jbr"
    version = "${file.jarVersion}"
    displayName = "Just Better Recipes"
    logoFile="pack.png"
    authors="sashiro"
    description = '''Just Better Recipes'''
